#!/usr/bin/python -tt
#
# Create a virtual machine from an XML image description
#
# Copyright 2007  Red Hat, Inc.
# David Lutterkort <dlutter@redhat.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301 USA.

import sys
import logging
import urlgrabber.progress as progress

import virtinst
import virtinst.ImageParser
import virtinst.CapabilitiesParser
import virtinst.cli as cli
from virtinst.cli import fail

import optparse
from optparse import OptionGroup

cli.setupGettext()

### General input gathering functions

def get_networks(domain, macs, bridges, networks, guest):
    nnics = domain.interface
    net_kwargs = cli.digest_networks(guest.conn, macs, bridges, networks,
                                     nnics)

    if len(net_kwargs) > nnics:
        logging.warn(_("Warning: more networks were provided [%i] then nics "
                       "required [%i]. All extras are ignored.") %
                       (len(net_kwargs), nnics))
        net_kwargs = net_kwargs[0:nnics]
    elif nnics > len(net_kwargs):
        fail(_("The image requires %i network interface.") % nnics)

    map(lambda kwargs: cli.get_network(kwargs, guest), net_kwargs)

def get_graphics(domain, vnc, vncport, vnclisten, nographics, sdl, keymap,
                 graphics, guest):
    if not domain.graphics:
        guest.graphics_dev = None
        return

    cli.get_graphics(vnc, vncport, vnclisten, nographics, sdl, keymap, [],
                     graphics, guest)

### Option parsing
def parse_args():
    usage = "%prog [options] image.xml"
    parser = cli.setupParser(usage)

    parser.add_option("", "--connect", type="string", dest="connect",
                      action="callback", callback=cli.check_before_store,
                      help=_("Connect to hypervisor with URI"),
                      default=None)

    geng = OptionGroup(parser, _("General Options"))
    geng.add_option("-n", "--name", type="string", dest="name",
                    action="callback", callback=cli.check_before_store,
                    help=_("Name of the guest instance"))
    geng.add_option("-r", "--ram", type="int", dest="memory",
                    help=_("Memory to allocate for guest instance in "
                           "megabytes"))
    geng.add_option("-u", "--uuid", type="string", dest="uuid",
                    action="callback", callback=cli.check_before_store,
                    help=_("UUID for the guest."))
    cli.vcpu_cli_options(geng)
    geng.add_option("", "--os-type", type="string", dest="distro_type",
                    action="callback", callback=cli.check_before_store,
                    help=_("The OS type being installed, e.g. "
                           "'linux', 'unix', 'windows'"))
    geng.add_option("", "--os-variant", type="string", dest="distro_variant",
                      action="callback", callback=cli.check_before_store,
                      help=_("The OS variant being installed, "
                             "e.g. 'fedora6', 'rhel5', 'solaris10', 'win2k'"))
    parser.add_option_group(geng)

    fulg = OptionGroup(parser, _("Full Virtualization specific options"))
    fulg.add_option("", "--noapic", action="store_true", dest="noapic",
                    default=False,
                    help=_("Disables APIC for fully virtualized guest"))
    fulg.add_option("", "--noacpi", action="store_true", dest="noacpi",
                    default=False,
                    help=_("Disables ACPI for fully virtualized guest"))
    parser.add_option_group(fulg)

    netg = OptionGroup(parser, _("Networking Configuration"))
    netg.add_option("-w", "--network", type="string", dest="network",
                    action="callback", callback=cli.check_before_append,
      help=_("Specify a network interface. Ex:\n"
             "--network bridge=mybr0\n"
             "--network network=libvirt_network_name\n"
             "--network network=mynet,model=e1000,mac=00:11..."))

    # Deprecated net options
    netg.add_option("-b", "--bridge", type="string", dest="bridge",
                    action="callback", callback=cli.check_before_append,
                    help=optparse.SUPPRESS_HELP)
    netg.add_option("-m", "--mac", type="string", dest="mac",
                    action="callback", callback=cli.check_before_append,
                    help=optparse.SUPPRESS_HELP)
    parser.add_option_group(netg)

    vncg = cli.graphics_option_group(parser)
    parser.add_option_group(vncg)

    misc = OptionGroup(parser, _("Miscellaneous Options"))
    misc.add_option("-p", "--print", action="store_true", dest="print_only",
                    help=_("Print the libvirt XML, but do not start the "
                           "domain"))
    misc.add_option("", "--boot", type="int", dest="boot",
                    help=_("The zero-based index of the boot record to use"))
    misc.add_option("", "--replace", action="store_true", dest="replace",
                    help=_("Overwrite, or destroy, an existing image with "
                           "the same name"),
                    default=False)
    misc.add_option("", "--skip-checksum", action="store_true",
                    dest="skipchecksum",
                    help=_("Skip disk checksum verification process"))
    misc.add_option("-d", "--debug", action="store_true", dest="debug",
                    help=_("Print debugging information"))
    misc.add_option("", "--prompt", action="store_true", dest="prompt",
                    help=optparse.SUPPRESS_HELP, default=False)
    misc.add_option("", "--force", action="store_true", dest="force",
                    help=_("Do not prompt for input. Answers yes where "
                           "applicable, terminates for all other prompts"),
                    default=False)
    parser.add_option_group(misc)

    (options, args) = parser.parse_args()

    if len(args) < 1:
        parser.error(_("You need to provide an image XML descriptor"))
    options.image = args[0]

    return options

def main():
    cli.earlyLogging()
    options = parse_args()

    cli.setupLogging("virt-image", options.debug)
    cli.set_prompt(options.prompt)
    cli.set_force(options.force)

    conn = cli.getConnection(options.connect)

    try:
        image = virtinst.ImageParser.parse_file(options.image)
    except virtinst.ImageParser.ParserException, msg:
        fail( "%s '%s': %s" % (_("Cannot parse"),  options.image, msg))

    if options.boot is not None:
        nboots = len(image.domain.boots)
        if options.boot < 0 or options.boot >= nboots:
            fail(_("The index for --boot must be between 0 and %d") %
                 (nboots - 1))


    # Build the Installer instance
    installer = virtinst.ImageInstaller(boot_index=options.boot,
                                        image=image,
                                        conn=conn)


    # Get Guest instance from installer parameters.
    guest = installer.guest_from_installer()


    # now let's get some of the common questions out of the way
    guest.replace = options.replace
    cli.get_name(options.name, guest, image.name)
    cli.get_memory(options.memory, guest, image.domain.memory)
    cli.get_uuid(options.uuid, guest)
    cli.get_vcpus(options.vcpus, options.check_cpu,
                  guest, conn, image.domain.vcpu)
    # For now, we only allow one NIC
    get_networks(image.domain, options.mac, options.bridge,
                 options.network, guest)

    get_graphics(image.domain, options.vnc, options.vncport, options.vnclisten,
                 options.nographics, options.sdl, options.keymap,
                 options.graphics, guest)

    cli.set_os_variant(guest, options.distro_type, options.distro_variant)

    if installer.is_hvm():
        if options.noacpi:
            guest.features["acpi"] = False
        if options.noapic:
            guest.features["apic"] = False

    if not options.skipchecksum:
        meter = progress.TextMeter()
        for disk in image.storage.values():
            disk.check_disk_signature(meter=meter)


    # we've got everything -- try to start the install
    if options.print_only:
        start_xml, final_xml = guest.start_install(return_xml=True)
        print start_xml or final_xml
        return
    try:
        progresscb = progress.TextMeter()

        print _("\n\nCreating guest %s...") % guest.name

        dom = guest.start_install(None, progresscb)
        if dom is None:
            print _("Guest creation failed")
            sys.exit(1)

    except RuntimeError:
        raise
    except Exception, e:
        fail(e, do_exit=False)
        print
        print _("Domain creation may not have been\n"
                "successful.  If it was, you can restart your domain\n"
                "by running 'virsh start %s'; otherwise, please\n"
                "restart your installation.") % guest.name
        sys.exit(1)

if __name__ == "__main__":
    try:
        main()
    except SystemExit, sys_e:
        sys.exit(sys_e.code)
    except KeyboardInterrupt:
        print >> sys.stderr, _("Installation aborted at user request")
    except Exception, main_e:
        fail(main_e)
