# Host keytable entry : keymap name in qemu/xen
keytable = {
    "ar":"ar",
    "dk":"da", "da":"da",
    "de":"de",
    "de-ch":"de-ch",
    "gb":"en-gb", "en-gb":"en-gb",
    "us":"en-us", "en-us":"en-us",
    "es":"es",
    "et":"et",
    "se_FI":"fi", "fi":"fi",
    "fo":"fo",
    "fr":"fr",
    "be":"fr-be","fr-be":"fr-be",
    "fr-ca":"fr-ca",
    "fr_CH":"fr_ch", "fr_ch":"fr_ch",
    "hr":"hr",
    "hu":"hu",
    "is":"is",
    "it":"it",
    "jp106":"ja", "ja":"ja",
    "lt":"lt",
    "lv":"lv",
    "mk":"mk",
    "nl": "nl",
    "nl-be":"nl-be",
    "no":"no",
    "pl":"pl",
    "pt":"pt",
    "br":"pt-br", "pt-br":"pt-br", "br-abnt2":"pt-br",
    "ru":"ru",
    "sl":"sl",
    "sv":"sv",
    "th":"th",
    "tr":"tr",
    }

